-- MySQL Script generated by MySQL Workbench
-- Fri Feb 17 00:51:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projekt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projekt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projekt` DEFAULT CHARACTER SET utf8 ;
USE `projekt` ;

-- -----------------------------------------------------
-- Table `projekt`.`szkola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`szkola` (
  `id_szkola` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(128) NOT NULL,
  `adres` VARCHAR(128) NOT NULL,
  `czy_prywatna` TINYINT(1) NOT NULL DEFAULT 0,
  `liczba_uczniow` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_szkola`),
  UNIQUE INDEX `id_szkola_UNIQUE` (`id_szkola` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`klasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`klasa` (
  `id_klasa` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NOT NULL,
  `id_szkola` INT NOT NULL,
  PRIMARY KEY (`id_klasa`),
  UNIQUE INDEX `id_klasa_UNIQUE` (`id_klasa` ASC),
  INDEX `fk_klasa_szkola_idx` (`id_szkola` ASC),
  CONSTRAINT `fk_klasa_szkola`
    FOREIGN KEY (`id_szkola`)
    REFERENCES `projekt`.`szkola` (`id_szkola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`uczen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`uczen` (
  `id_uczen` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NOT NULL,
  `nazwisko` VARCHAR(45) NOT NULL,
  `wiek` INT NOT NULL,
  `id_klasa` INT NOT NULL,
  PRIMARY KEY (`id_uczen`),
  UNIQUE INDEX `id_uczen_UNIQUE` (`id_uczen` ASC),
  INDEX `fk_uczen_klasa1_idx` (`id_klasa` ASC),
  CONSTRAINT `fk_uczen_klasa1`
    FOREIGN KEY (`id_klasa`)
    REFERENCES `projekt`.`klasa` (`id_klasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`przedmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`przedmiot` (
  `id_przedmiot` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_przedmiot`),
  UNIQUE INDEX `id_przedmiot_UNIQUE` (`id_przedmiot` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt`.`ocena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projekt`.`ocena` (
  `id_ocena` INT NOT NULL AUTO_INCREMENT,
  `ocena` INT NOT NULL,
  `dataWystawienia` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_uczen` INT NOT NULL,
  `id_przedmiot` INT NOT NULL,
  PRIMARY KEY (`id_ocena`),
  UNIQUE INDEX `id_ocena_UNIQUE` (`id_ocena` ASC),
  INDEX `fk_ocena_uczen1_idx` (`id_uczen` ASC),
  INDEX `fk_ocena_przedmiot1_idx` (`id_przedmiot` ASC),
  CONSTRAINT `fk_ocena_uczen1`
    FOREIGN KEY (`id_uczen`)
    REFERENCES `projekt`.`uczen` (`id_uczen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocena_przedmiot1`
    FOREIGN KEY (`id_przedmiot`)
    REFERENCES `projekt`.`przedmiot` (`id_przedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
